name: sync from git.pyliubaolin.top

on: 
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -en "StrictHostKeyChecking no\n\nHost git.pyliubaolin.top\nHostName git.pyliubaolin.top\nPort 2233" >> ~/.ssh/config
      - name: Push Mirror
        env:
          SOURCE_REPO: 'git@git.pyliubaolin.top:Gardenia/genes_framework.git'
          DESTINATION_REPO: 'git@github.com:lzhbhlrPython/genes_framework.git'
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror